### ISSUE TITLE
readiness probes failing

### ISSUE THREAD

**Issue by TomasTomecek** [packit/tokman#51]
```
Feb 21, 2023, 6:11 PM
Generated from kubelet on ip-10-0-150-231.eu-west-1.compute.internal
445 times in the last 7 days
Liveness probe failed: Get "http://10.130.27.204:8000/api/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

```
Feb 21, 2023, 6:11 PM
Generated from kubelet on ip-10-0-150-231.eu-west-1.compute.internal
886 times in the last 7 days
Readiness probe failed: Get "http://10.130.27.204:8000/api/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

I can see a bunch of exceptions in logs:
```
ERROR:tokman.app:Exception on /api/TLCFEM/suanPan [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/tokman/tokman/app.py", line 113, in get
    token.token, token.expires_at = get_token(namespace, repository)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tokman/tokman/app.py", line 88, in get_token
    inst_id = current_app.github_integration.get_installation(namespace, repository).id
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/github/MainClass.py", line 883, in get_installation
    response_dict = response.json()
                    ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/tokman/tokman/app.py", line 113, in get
    token.token, token.expires_at = get_token(namespace, repository)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tokman/tokman/app.py", line 92, in get_token
    inst_auth = current_app.github_integration.get_access_token(inst_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/github/MainClass.py", line 862, in get_access_token
    raise GithubException.GithubException(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GithubException.__init__() missing 1 required positional argument: 'headers'
```

**Comment by csomh** [comment]
I'm having a look into this.

**Comment by csomh** [comment]
Here is what I found:

I think the exceptions in the logs and readiness probe failing are unrelated issues.

The JSONDecoderError is simply b/c of decoding errors being [re-raised by PyGithub](https://github.com/PyGithub/PyGithub/commit/916da53bef20b0ffa221ba8f2f5c28f30c27a578). As the commit message says, GitHub sometimes returns just plain text, instead of a JSON string. [Checking Sentry](https://red-hat-it.sentry.io/issues/3944574555/events/ba3eb360f1d94f68900107d902502575/?project=1767823), it seems that this was happening around a time when GitHub was responding with "internal error".

The second exception is probably a 2 years old bug in PyGithub: [`GithubException` received a `header` argument](https://github.com/PyGithub/PyGithub/commit/ddd437a7cdcc806670d9ce76f46812d30f1d6c1a), but this seems to be never updated in the `get_accesss_token` path. Probably we were hitting this before also, we just didn't notice. This was also triggered by the same GitHub 500. The bug is gone in 1.58, which made GitHub App auth a first class citizen. Old interfaces are still in place, but  they behave a little differently. I'll open a PR to fix this.

The health API not responding or taking long to respond is probably due to the fact that we are calling GitHub so much, and the only Gunicorn worker gets overwhelmed. I'll update the deployment to use 2 workers instead, and let's see if this helps with the health api being more responsive.

**Comment by TomasTomecek** [comment]
Thank you for the detailed write-up! Agreed with all.

When I created this issue yesterday, it was just a "braindump" before me zoning out.

**Comment by jpopelka** [comment]
> The health API not responding or taking long to respond is probably due to the fact that we are calling GitHub so much, and the only Gunicorn worker gets overwhelmed. I'll update the deployment to use 2 workers instead, and let's see if this helps with the health api being more responsive.

Looking forward to seeing it in action.

I've just found one of the [Event PullRequestGithubEvent took (Xs) to process.](https://red-hat-it.sentry.io/issues/3952215912) with complete breadcrumbs list and it show, that the bottleneck (14:36:51 - 14:37:55) was tokman.

I already noticed this some time ago, but haven't created a card for it so I almost forgot.

```
On 1/6/23 14:01, Jiri Popelka wrote:
> There were several of those (SLO1 ErrorBudgetBurn) in the last days.
> 
> In some cases the problem seems to be that
> it took tokman over a minute to get a new token
> GET http://tokman/api/teemtee/tmt [200] 12:47:28 -> 12:48:32
```

**Comment by csomh** [comment]
Note that the readiness probe and liveness probe timeouts are not fatal in the sense that they don't happen often enough (3 times in a row) for the pod to be restarted... at least not that often. Still, the performance impact is clear.

Experiment 0: increase number of workers to 2. — This caused a memory pressure.

Experiment 1: Increase memory request to 128/164Mi - Still quite a lot of liveness and readiness probe timeouts.

Experiment 2: Increase CPU request to 20m - 5 readiness probe failures in an hour, in a quire busy period. CPU is around 50% of the request, memory is somewhat above the request line, but below the limit.

Experiment 3: Increase memory to 160/224Mi. Switch readinessProbe to startupProbe. — The startupProbe timed out twice, but there was one single livenessProbe timeout in an hour.

... some more experiments to come.

**Comment by csomh** [comment]
One thing to note: I'm somewhat not sure if having multiple workers won't trigger a race condition, and lead to invalidating tokens that were just retrieved. Although I've seen no such thing happening in the logs.

**Comment by csomh** [comment]
@TomasTomecek now that packit/deployment#458 and #52 is merged, do you think there is anything else left to do with this issue?
